import { Variable } from '@tamagui/web';
export { darkColor, darkPalette, darkTransparent, lightColor, lightPalette, lightTransparent, } from './colors';
export declare const colorTokens: {
    light: {
        blue: {
            blue1: string;
            blue2: string;
            blue3: string;
            blue4: string;
            blue5: string;
            blue6: string;
            blue7: string;
            blue8: string;
            blue9: string;
            blue10: string;
            blue11: string;
            blue12: string;
        };
        gray: {
            gray1: string;
            gray2: string;
            gray3: string;
            gray4: string;
            gray5: string;
            gray6: string;
            gray7: string;
            gray8: string;
            gray9: string;
            gray10: string;
            gray11: string;
            gray12: string;
        };
        green: {
            green1: string;
            green2: string;
            green3: string;
            green4: string;
            green5: string;
            green6: string;
            green7: string;
            green8: string;
            green9: string;
            green10: string;
            green11: string;
            green12: string;
        };
        orange: {
            orange1: string;
            orange2: string;
            orange3: string;
            orange4: string;
            orange5: string;
            orange6: string;
            orange7: string;
            orange8: string;
            orange9: string;
            orange10: string;
            orange11: string;
            orange12: string;
        };
        pink: {
            pink1: string;
            pink2: string;
            pink3: string;
            pink4: string;
            pink5: string;
            pink6: string;
            pink7: string;
            pink8: string;
            pink9: string;
            pink10: string;
            pink11: string;
            pink12: string;
        };
        purple: {
            purple1: string;
            purple2: string;
            purple3: string;
            purple4: string;
            purple5: string;
            purple6: string;
            purple7: string;
            purple8: string;
            purple9: string;
            purple10: string;
            purple11: string;
            purple12: string;
        };
        red: {
            red1: string;
            red2: string;
            red3: string;
            red4: string;
            red5: string;
            red6: string;
            red7: string;
            red8: string;
            red9: string;
            red10: string;
            red11: string;
            red12: string;
        };
        yellow: {
            yellow1: string;
            yellow2: string;
            yellow3: string;
            yellow4: string;
            yellow5: string;
            yellow6: string;
            yellow7: string;
            yellow8: string;
            yellow9: string;
            yellow10: string;
            yellow11: string;
            yellow12: string;
        };
    };
    dark: {
        blue: {
            blue1: string;
            blue2: string;
            blue3: string;
            blue4: string;
            blue5: string;
            blue6: string;
            blue7: string;
            blue8: string;
            blue9: string;
            blue10: string;
            blue11: string;
            blue12: string;
        };
        gray: {
            gray1: string;
            gray2: string;
            gray3: string;
            gray4: string;
            gray5: string;
            gray6: string;
            gray7: string;
            gray8: string;
            gray9: string;
            gray10: string;
            gray11: string;
            gray12: string;
        };
        green: {
            green1: string;
            green2: string;
            green3: string;
            green4: string;
            green5: string;
            green6: string;
            green7: string;
            green8: string;
            green9: string;
            green10: string;
            green11: string;
            green12: string;
        };
        orange: {
            orange1: string;
            orange2: string;
            orange3: string;
            orange4: string;
            orange5: string;
            orange6: string;
            orange7: string;
            orange8: string;
            orange9: string;
            orange10: string;
            orange11: string;
            orange12: string;
        };
        pink: {
            pink1: string;
            pink2: string;
            pink3: string;
            pink4: string;
            pink5: string;
            pink6: string;
            pink7: string;
            pink8: string;
            pink9: string;
            pink10: string;
            pink11: string;
            pink12: string;
        };
        purple: {
            purple1: string;
            purple2: string;
            purple3: string;
            purple4: string;
            purple5: string;
            purple6: string;
            purple7: string;
            purple8: string;
            purple9: string;
            purple10: string;
            purple11: string;
            purple12: string;
        };
        red: {
            red1: string;
            red2: string;
            red3: string;
            red4: string;
            red5: string;
            red6: string;
            red7: string;
            red8: string;
            red9: string;
            red10: string;
            red11: string;
            red12: string;
        };
        yellow: {
            yellow1: string;
            yellow2: string;
            yellow3: string;
            yellow4: string;
            yellow5: string;
            yellow6: string;
            yellow7: string;
            yellow8: string;
            yellow9: string;
            yellow10: string;
            yellow11: string;
            yellow12: string;
        };
    };
};
export declare const darkColors: {
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const lightColors: {
    yellow1: string;
    yellow2: string;
    yellow3: string;
    yellow4: string;
    yellow5: string;
    yellow6: string;
    yellow7: string;
    yellow8: string;
    yellow9: string;
    yellow10: string;
    yellow11: string;
    yellow12: string;
    red1: string;
    red2: string;
    red3: string;
    red4: string;
    red5: string;
    red6: string;
    red7: string;
    red8: string;
    red9: string;
    red10: string;
    red11: string;
    red12: string;
    purple1: string;
    purple2: string;
    purple3: string;
    purple4: string;
    purple5: string;
    purple6: string;
    purple7: string;
    purple8: string;
    purple9: string;
    purple10: string;
    purple11: string;
    purple12: string;
    pink1: string;
    pink2: string;
    pink3: string;
    pink4: string;
    pink5: string;
    pink6: string;
    pink7: string;
    pink8: string;
    pink9: string;
    pink10: string;
    pink11: string;
    pink12: string;
    orange1: string;
    orange2: string;
    orange3: string;
    orange4: string;
    orange5: string;
    orange6: string;
    orange7: string;
    orange8: string;
    orange9: string;
    orange10: string;
    orange11: string;
    orange12: string;
    green1: string;
    green2: string;
    green3: string;
    green4: string;
    green5: string;
    green6: string;
    green7: string;
    green8: string;
    green9: string;
    green10: string;
    green11: string;
    green12: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    gray10: string;
    gray11: string;
    gray12: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    blue11: string;
    blue12: string;
};
export declare const color: {
    blue1Dark: string | Variable<string>;
    blue2Dark: string | Variable<string>;
    blue3Dark: string | Variable<string>;
    blue4Dark: string | Variable<string>;
    blue5Dark: string | Variable<string>;
    blue6Dark: string | Variable<string>;
    blue7Dark: string | Variable<string>;
    blue8Dark: string | Variable<string>;
    blue9Dark: string | Variable<string>;
    blue10Dark: string | Variable<string>;
    blue11Dark: string | Variable<string>;
    blue12Dark: string | Variable<string>;
    gray1Dark: string | Variable<string>;
    gray2Dark: string | Variable<string>;
    gray3Dark: string | Variable<string>;
    gray4Dark: string | Variable<string>;
    gray5Dark: string | Variable<string>;
    gray6Dark: string | Variable<string>;
    gray7Dark: string | Variable<string>;
    gray8Dark: string | Variable<string>;
    gray9Dark: string | Variable<string>;
    gray10Dark: string | Variable<string>;
    gray11Dark: string | Variable<string>;
    gray12Dark: string | Variable<string>;
    green1Dark: string | Variable<string>;
    green2Dark: string | Variable<string>;
    green3Dark: string | Variable<string>;
    green4Dark: string | Variable<string>;
    green5Dark: string | Variable<string>;
    green6Dark: string | Variable<string>;
    green7Dark: string | Variable<string>;
    green8Dark: string | Variable<string>;
    green9Dark: string | Variable<string>;
    green10Dark: string | Variable<string>;
    green11Dark: string | Variable<string>;
    green12Dark: string | Variable<string>;
    orange1Dark: string | Variable<string>;
    orange2Dark: string | Variable<string>;
    orange3Dark: string | Variable<string>;
    orange4Dark: string | Variable<string>;
    orange5Dark: string | Variable<string>;
    orange6Dark: string | Variable<string>;
    orange7Dark: string | Variable<string>;
    orange8Dark: string | Variable<string>;
    orange9Dark: string | Variable<string>;
    orange10Dark: string | Variable<string>;
    orange11Dark: string | Variable<string>;
    orange12Dark: string | Variable<string>;
    pink1Dark: string | Variable<string>;
    pink2Dark: string | Variable<string>;
    pink3Dark: string | Variable<string>;
    pink4Dark: string | Variable<string>;
    pink5Dark: string | Variable<string>;
    pink6Dark: string | Variable<string>;
    pink7Dark: string | Variable<string>;
    pink8Dark: string | Variable<string>;
    pink9Dark: string | Variable<string>;
    pink10Dark: string | Variable<string>;
    pink11Dark: string | Variable<string>;
    pink12Dark: string | Variable<string>;
    purple1Dark: string | Variable<string>;
    purple2Dark: string | Variable<string>;
    purple3Dark: string | Variable<string>;
    purple4Dark: string | Variable<string>;
    purple5Dark: string | Variable<string>;
    purple6Dark: string | Variable<string>;
    purple7Dark: string | Variable<string>;
    purple8Dark: string | Variable<string>;
    purple9Dark: string | Variable<string>;
    purple10Dark: string | Variable<string>;
    purple11Dark: string | Variable<string>;
    purple12Dark: string | Variable<string>;
    red1Dark: string | Variable<string>;
    red2Dark: string | Variable<string>;
    red3Dark: string | Variable<string>;
    red4Dark: string | Variable<string>;
    red5Dark: string | Variable<string>;
    red6Dark: string | Variable<string>;
    red7Dark: string | Variable<string>;
    red8Dark: string | Variable<string>;
    red9Dark: string | Variable<string>;
    red10Dark: string | Variable<string>;
    red11Dark: string | Variable<string>;
    red12Dark: string | Variable<string>;
    yellow1Dark: string | Variable<string>;
    yellow2Dark: string | Variable<string>;
    yellow3Dark: string | Variable<string>;
    yellow4Dark: string | Variable<string>;
    yellow5Dark: string | Variable<string>;
    yellow6Dark: string | Variable<string>;
    yellow7Dark: string | Variable<string>;
    yellow8Dark: string | Variable<string>;
    yellow9Dark: string | Variable<string>;
    yellow10Dark: string | Variable<string>;
    yellow11Dark: string | Variable<string>;
    yellow12Dark: string | Variable<string>;
    blue1Light: string | Variable<string>;
    blue2Light: string | Variable<string>;
    blue3Light: string | Variable<string>;
    blue4Light: string | Variable<string>;
    blue5Light: string | Variable<string>;
    blue6Light: string | Variable<string>;
    blue7Light: string | Variable<string>;
    blue8Light: string | Variable<string>;
    blue9Light: string | Variable<string>;
    blue10Light: string | Variable<string>;
    blue11Light: string | Variable<string>;
    blue12Light: string | Variable<string>;
    gray1Light: string | Variable<string>;
    gray2Light: string | Variable<string>;
    gray3Light: string | Variable<string>;
    gray4Light: string | Variable<string>;
    gray5Light: string | Variable<string>;
    gray6Light: string | Variable<string>;
    gray7Light: string | Variable<string>;
    gray8Light: string | Variable<string>;
    gray9Light: string | Variable<string>;
    gray10Light: string | Variable<string>;
    gray11Light: string | Variable<string>;
    gray12Light: string | Variable<string>;
    green1Light: string | Variable<string>;
    green2Light: string | Variable<string>;
    green3Light: string | Variable<string>;
    green4Light: string | Variable<string>;
    green5Light: string | Variable<string>;
    green6Light: string | Variable<string>;
    green7Light: string | Variable<string>;
    green8Light: string | Variable<string>;
    green9Light: string | Variable<string>;
    green10Light: string | Variable<string>;
    green11Light: string | Variable<string>;
    green12Light: string | Variable<string>;
    orange1Light: string | Variable<string>;
    orange2Light: string | Variable<string>;
    orange3Light: string | Variable<string>;
    orange4Light: string | Variable<string>;
    orange5Light: string | Variable<string>;
    orange6Light: string | Variable<string>;
    orange7Light: string | Variable<string>;
    orange8Light: string | Variable<string>;
    orange9Light: string | Variable<string>;
    orange10Light: string | Variable<string>;
    orange11Light: string | Variable<string>;
    orange12Light: string | Variable<string>;
    pink1Light: string | Variable<string>;
    pink2Light: string | Variable<string>;
    pink3Light: string | Variable<string>;
    pink4Light: string | Variable<string>;
    pink5Light: string | Variable<string>;
    pink6Light: string | Variable<string>;
    pink7Light: string | Variable<string>;
    pink8Light: string | Variable<string>;
    pink9Light: string | Variable<string>;
    pink10Light: string | Variable<string>;
    pink11Light: string | Variable<string>;
    pink12Light: string | Variable<string>;
    purple1Light: string | Variable<string>;
    purple2Light: string | Variable<string>;
    purple3Light: string | Variable<string>;
    purple4Light: string | Variable<string>;
    purple5Light: string | Variable<string>;
    purple6Light: string | Variable<string>;
    purple7Light: string | Variable<string>;
    purple8Light: string | Variable<string>;
    purple9Light: string | Variable<string>;
    purple10Light: string | Variable<string>;
    purple11Light: string | Variable<string>;
    purple12Light: string | Variable<string>;
    red1Light: string | Variable<string>;
    red2Light: string | Variable<string>;
    red3Light: string | Variable<string>;
    red4Light: string | Variable<string>;
    red5Light: string | Variable<string>;
    red6Light: string | Variable<string>;
    red7Light: string | Variable<string>;
    red8Light: string | Variable<string>;
    red9Light: string | Variable<string>;
    red10Light: string | Variable<string>;
    red11Light: string | Variable<string>;
    red12Light: string | Variable<string>;
    yellow1Light: string | Variable<string>;
    yellow2Light: string | Variable<string>;
    yellow3Light: string | Variable<string>;
    yellow4Light: string | Variable<string>;
    yellow5Light: string | Variable<string>;
    yellow6Light: string | Variable<string>;
    yellow7Light: string | Variable<string>;
    yellow8Light: string | Variable<string>;
    yellow9Light: string | Variable<string>;
    yellow10Light: string | Variable<string>;
    yellow11Light: string | Variable<string>;
    yellow12Light: string | Variable<string>;
};
//# sourceMappingURL=token-colors.d.ts.map